### ISSUE TITLE
Implementing the same in React to be more inclusive

### ISSUE THREAD

**Issue by darshan-k-s** [IonicaBizau/default-page#16]
## Implement the same page in React:
Since the implementation is already done with HTML and CSS, it would also be helpful to implement the same with React. It's very commonly used by developers.

You could go through an example implementation here:
[Implementation on CodePen](https://codepen.io/darshan-k-5/pen/QWgPpKv)

We could of course customize it however we want.

This can also be expanded to multiple front-end frameworks, but I'm pitching the idea to do it in React first. [](url)

**Comment by IonicaBizau** [comment]
Umm, but why would anyone prefer to deploy a react page instead of the HTML version which is quite minimal?

**Comment by darshan-k-s** [comment]
I'm not saying that we would replace the existing version. Just saying that we can include both versions in the same repo so that people have a choice.

**Comment by IonicaBizau** [comment]
Yes, we could definitely add that. Thanks <3

**Comment by IonicaBizau** [comment]
Thank you
